// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	app_context "github.com/cuongtranba/mynoti/pkg/app_context"

	mock "github.com/stretchr/testify/mock"
)

// HtmlFetcher is an autogenerated mock type for the HtmlFetcher type
type HtmlFetcher struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, url
func (_m *HtmlFetcher) Fetch(ctx *app_context.AppContext, url string) (string, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*app_context.AppContext, string) (string, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(*app_context.AppContext, string) string); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*app_context.AppContext, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHtmlFetcher creates a new instance of HtmlFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHtmlFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *HtmlFetcher {
	mock := &HtmlFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
