// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package comic

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ComicTracking struct {
	ID          int32
	Url         string
	Name        pgtype.Text
	Description pgtype.Text
	Html        pgtype.Text
	LastChecked pgtype.Timestamp
}
